color=input("Enter a color: ")

match color:
    case "red":       print("The color is red")
    case "blue":      print("The color is blue")
    case "green":     print("The color is green")
    case "yellow":    print("The color is yellow")
    case "orange":    print("The color is orange")
    case "purple":    print("The color is purple")
    case "pink":      print("The color is pink")
    case "black":     print("The color is black")
    case "white":     print("The color is white")
    case "gray":      print("The color is gray")
    case "brown":     print("The color is brown")
    case "cyan":      print("The color is cyan")
    case "magenta":   print("The color is magenta")
    case "maroon":    print("The color is maroon")
    case "navy":      print("The color is navy")
    case _ :             print("The color is not in the list")